# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61d6338955680560e69e86c35b31cf9812fbe7bc5cc85dabaae5cf6466ba1adf980a915500e914c4f565dededa7e80e06041f6e907c8d472a13276529ddb91a1

test:
  secret_key_base: c23b339b221741a3aafd95813883a9b520a2c989448e47b49a56a9f87f25a469408570985991d7b0d2ca98f23c0fa5af314d3d8ef2c7f92e8ebb6c485c8d1cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
